### PR TITLE
Browserify support

### PR DESCRIPTION
**Pull request by hugomrdias**

### CODE REVIEW

**Comment by cesarandreu** [comment]
+1

**Comment by jmagnusson** [comment]
Worked for me.

**Comment by eoger** [comment]
@hugomrdias, could you remove the last commit (there is already is similar one : https://github.com/blueimp/JavaScript-Canvas-to-Blob/commit/e6734055af22e23009ca15ff604b9a5e7d57319c) so @blueimp can merge this?

**Comment by D34THWINGS** [comment]
+1

**Comment by devnieL** [comment]
+1

**Pull request closed without merging**
